package com.chocolatada.keyvault.crypto

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import java.security.KeyStore
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey

class KeyStoreUtil {
    companion object {
        //this is only an alias
        //the value of the key is generated by the TEE (hardware) and we have no way to know its value
        val KEY_ALIAS = "secret"

        val INSTANCE_TYPE = "AndroidKeyStore"

        fun getSecretKey(): SecretKey {
            val keyStore = getKeyStore()
            return keyStore.getKey(KEY_ALIAS, null) as SecretKey
        }

        fun getKeyStore(): KeyStore {
            return KeyStore.getInstance(INSTANCE_TYPE).apply {
                load(null)
            }
        }

        fun createKeyIfNotExists() {
            val keyStore = getKeyStore()

            if (keyStore.containsAlias(KEY_ALIAS)) return

            val keyGenerator = KeyGenerator.getInstance(
                KeyProperties.KEY_ALGORITHM_AES,
                INSTANCE_TYPE
            )

            //spec contains the properties of the key we are about to generate
            val spec = KeyGenParameterSpec.Builder(
                KEY_ALIAS,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(256)
                .build()

            keyGenerator.init(spec)
            //registers the key in the TEE (hardware) with our alias
            //the key is randomly generated by the TEE, and we have no way to know its value
            keyGenerator.generateKey()
        }
    }
}